EzClinicWeb/Models/Patient.cs
namespace EzClinicWeb.Models
{
    using System;

    public class Patient
    {
        public int PatientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public Int64 MobileNo { get; set; }
        public string Email { get; set; }
        public string NfcReference { get; set; }
        public string CreditCardType { get; set; }
        public Int64 CreditCardNo { get; set; }
        public int CreditCardExpMonth { get; set; }
        public int CreditCardExpYear { get; set; }
        public string NameOnCard { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public int IsActive { get; set; }
        public int Password { get; set; }
    }
}

EzClinicWeb/Models/PatientDetailsForResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EzClinicWeb.Models
{
    public class PatientDetailsForResponse
    {
        public int PatientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Int64 MobileNo { get; set; }
        public string Message { get; set; }
    }
}

EzClinicWeb/Controllers/HomeController.cs
namespace EzClinicWeb.Controllers
{
    using System.Web.Mvc;

    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Welcome()
        {
            return View();
        }
    }
}

EzClinicWeb/Controllers/PatientController.cs
namespace EzClinicWeb.Controllers
{
    using System;   
    using System.Web.Mvc;

    public class PatientController : Controller
    {
        /*public ActionResult Index()
        {
            return View();
        }

        public ActionResult PatientDetails(int? id)
        {
            return View(id);
        }*/

        public ActionResult RegisterPatient()
        {
            return View();
        }

        public ActionResult RegConfirmation()
        {
            return View();
        }

        /* public ActionResult Register()
         {
             return View("RegisterPatient");
         }Demo in comments*/
    }
}

EzClinicWeb/Views/Home/Welcome.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<!DOCTYPE HTML>
<html>
<head runat="server">
    <title>EZClinic</title>
    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
    <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0;  user-scalable=0;" name="viewport">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
    <style>

 html {
  background: url(../../../../images/doctor-ipad.jpg) no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
	.row {
  margin-left: 0px;
  margin-right: 0px;
}
body { overflow-x: hidden;}
.container {
    padding-right: 15px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto;
	background-color:rgba(120, 83, 83, 0.49);
}
img {
height:100px;
  -webkit-filter: blur(2px);
  -moz-filter: blur(2px);
  -o-filter: blur(2px);
  -ms-filter: blur(2px);
  filter: blur(2px);
}

.caption {
    position: absolute;
    top: 45%;
    left: 0;
    width: 100%;
	margin-top:20px;
	background-color:rgba(164, 217, 237, 0.37);
	vertical-align:middle;
	background-size:cover;
	border-radius:7px;
  align-items: center;
  justify-content: center;
  padding:200px;
  font-weight:bold;
}

h2{font-weight:bolder; color:#000;}
.cul{font-weight:bolder; color:#000;}
.navbar{background-color:; margin-bottom:0px;}

@@media (max-width: 978px){
.caption{padding:30px; height:200px;align-items: center;justify-content: center; margin-top:100px;}
}
    </style>

</head>
<body width="device-width">
    <form id="form1" runat="server">
        <div id="divContainer">


            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">EZClinic</a>
                    </div>
                    <div class="collapse navbar-collapse" id="myNavbar">
                        <ul class="nav navbar-nav">
                           @* <li class="active"><a href="#">Home</a></li>
    <li><a href="Reg1.html">Registration</a></li>*@
                            @*<li><a href="Appointment.html">Appointment</a></li>*@
                            @*<li><a href="#">Help</a></li>*@
                        </ul>
                        @*<ul class="nav navbar-nav navbar-right">
                            <li><a href="Reg1.html"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                            <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                        </ul>*@
                    </div>
                </div>
            </nav>


            <div class='container'>
                <div class='row'>
                    <div class='col-md-12 text-center '>
                        <!-- <img src="cad1.jpg" alt="middle" id="img"> -->
                        <div class="caption post-content text-center ">

                            <h2>Welcome to EZClinic</h2>
                            <p class="text-center cul">Please tap your NFC or get your registration process done<span style="font-weight:bold;color:#000"> &#64;</span> frontdesk</p>

                        </div>
                    </div>
                </div>
            </div>



        </div>
    </form>
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>

EzClinicWeb/Views/Patient/RegConfirmation.cshtml
@{
    Layout = null;
}
@using System.Configuration;
<!DOCTYPE HTML>
<html>
<head runat="server">
    <title>EZClinic</title>
    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
    <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0;  user-scalable=0;" name="viewport">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>  
    
    <style>
       html { 
  background: url(../../../../images/tumbsUp.jpg) no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
	.row {
  margin-left: 0px;
  margin-right: 0px;
}
body { overflow-x: hidden;}
.container {
    padding-right: 15px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto;
	width:700px;
}
img {
height:100px;
  -webkit-filter: blur(2px);
  -moz-filter: blur(2px);
  -o-filter: blur(2px);
  -ms-filter: blur(2px);
  filter: blur(2px);
}

.caption {
    position: absolute;
    top: 45%;
    left: 0;
    width: 100%;
	margin-top:20px;	
	vertical-align:middle;
	background-size:cover;
	border-radius:7px;
  font-weight:bold;
}

.caption a{text-decoration:none;}
h3{font-weight:bold;}
.cul{font-weight:bolder; color:#0e62a0;}
.navbar{background-color:; margin-bottom:0px;}

.nopadding {
   padding-top: 10px !important;
   margin: 0 !important;
}

fieldset.fsStyle {
font-family: Verdana, Arial, sans-serif;
font-size: small;
font-weight: normal;
padding: 4px;
margin: 5px;
background-color:rgba(149, 220, 198, 0.59);
  border:2px solid green;
}

@@media (max-width: 978px){
.container {width:auto;}
}
    </style>

    <script>

        function PrintElem(elem) {
            Popup($(elem).html());
        }

        function Popup(data) {
            var mywindow = window.open('', '', 'height=400,width=500');
            mywindow.document.write('<html><head><title></title>');
            /*optional stylesheet*/ //mywindow.document.write('<link rel="stylesheet" href="main.css" type="text/css" />');
            /*mywindow.document.write('<style type="text/css"> #pheader{font-size:20px;font-weight:bold; padding:10px;text-align:center;} #pdR{font-size:16px;font-weight:bold; padding:10px;text-align:right;} #pdL{font-size:16px;font-weight:bold; padding:10px;text-align:Left;}</style>');*/
            mywindow.document.write('<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />');
            mywindow.document.write('</head><body >');
            mywindow.document.write(data);
            mywindow.document.write('</body></html>');

            mywindow.document.close(); // necessary for IE >= 10
            mywindow.focus(); // necessary for IE >= 10

            mywindow.print();
            mywindow.close();

            return true;
        }

function GetParameterValues(param) {
    var url = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
    for (var i = 0; i < url.length; i++) {
        var urlparam = url[i].split('=');
        if (urlparam[0] == param) {
            return urlparam[1];
        }
    }
}

$(document).ready(function () {
    debugger
    var name = GetParameterValues('FirstName') + ' ' + GetParameterValues('LastName');
    name = name.replace(",", " ");
    var id = GetParameterValues('PatientId').replace(",", " ");
    var mobile = GetParameterValues('MobileNo');
    $('#lblPatientName').html(name);
    $('#lblPatientId').html(id);
    $('#lblMobileNo').html(mobile);
    
});
    </script>

</head>
<body width="device-width">
   
    <form id="form1" runat="server">
        <div id="divContainer">


            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">EZClinic</a>
                    </div>
                    <div class="collapse navbar-collapse" id="myNavbar">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="@Url.Action("RegisterPatient", "Patient")">Registration</a></li>
                            <!---<li ><a href="#">Help</a></li>--->
                        </ul>
                        <ul class="nav navbar-nav navbar-right">

                            <!--- <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>--->
                        </ul>
                    </div>
                </div>
            </nav>


            <div class='padding container'>
                <div class='row'>
                    <div class='col-md-12 text-center '>
                        <!-- <img src="cad1.jpg" alt="middle" id="img"> -->
                        <div class="caption post-content text-center ">

                            <h3>Registration is Successful !!</h3>
                            <div class="row text-right" style="padding-right:20px;padding-bottom:20px;">
                                <a href="#" onclick="PrintElem('#mydiv')">
                                    <span class="glyphicon glyphicon-print"></span> Print
                                </a>
                            </div>
                            <div class='row form-group' id="mydiv">
                                <fieldset class="fsStyle" style=" border-radius:20px 20px;">

                                    <div class='col-md-12 col-sm-12 col-xs-12 text-center'>
                                        <div id="pheader" style="background-color:rgba(22, 122, 159, 0.71);border-radius:10px;">
                                            <p style="font-size:15px;font-weight:bold; padding:10px;">EZClinic</p>
                                        </div>

                                        <div class="row top5 nopadding">
                                            <div class="col-md-6 col-sm-6 col-xs-6 text-right ">
                                                <label for="PName" class="control-label">Patient Name:</label>
                                            </div>
                                            <div class="col-md-6 col-sm-6 col-xs-6 text-left ">
                                                <label id="lblPatientName" id="PName" name="PName"></label>     
                                            </div>
                                        </div>
                                        <div class="row top5 nopadding">
                                            <div class="col-md-6 col-sm-6 col-xs-6 text-right ">
                                                <label for="LastName" class="control-label">Patient ID:</label>
                                            </div>
                                            <div class="col-md-6 col-sm-6 col-xs-6 text-left">
                                                <label id="lblPatientId"></label>
                                            </div>
                                        </div>
                                        <!-- <div class="row top5">
                                            <div class="col-md-5 col-sm-5 col-xs-5 text-right nopadding">
                                                <label for="BGroup" class="control-label">Blood Group:</label>
                                            </div>
                                            <div class="col-md-7 col-sm-7 col-xs-7 text-left">
                                                <input readonly="readonly" type="text" id="BloodGroup" name="BGroup" class="form-control"/>
                                            </div>
                                        </div> -->

                                        <div class="row top5 nopadding">
                                            <div class="col-md-6 col-sm-6 col-xs-6 text-right ">
                                                <label for="Number" class="control-label">Contact Number:</label>
                                            </div>
                                            <div class="col-md-6 col-sm-6 col-xs-6 text-left ">
                                                <label id="lblMobileNo" for="MobileNo" name="MobileNo"></label>
                                            </div>
                                        </div>

                                    </div>

                                </fieldset>
                            </div>

                        </div>
                    </div>
                </div>
            </div>



        </div>
    </form>
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>


